kind: Service
apiVersion: v1
metadata:
  labels:
    service.name: tower32
  name: tower32
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 30001
    targetPort: 30001
  selector:
    service.name: tower32
